"""empty message

Revision ID: bf8625e88136
Revises: 
Create Date: 2026-05-10 10:51:05.978194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8625e88136'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('email', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('avatar', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('password', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=True),
    sa.Column('password_salt', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('last_login_ip', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_account_id')
    )
    op.create_table('account_oauth',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('openid', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('encrypted_token', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_account_oauth_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_oauth')
    op.drop_table('account')
    # ### end Alembic commands ###
